title: Harry Craven
logo: assets/img/Harry_Craven_DMA_Profile_Photo.jpg
description: Collection of ongoing PhD & personal work
show_downloads: false
theme: jekyll-theme-minimal
favicon: favicon-32x32.png
